- name: "textarea"
  type: "jQuery Object / HTML Element / Selector String"
  default: "null"
  description: |
    指定用来初始化编辑器的 `textarea` 元素，可以接受 jQuery Object、HTML Element 或者 Selector String 类型的参数。

- name: "placeholder"
  type: "String"
  default: "''"
  description: |
    编辑器的 placeholder，如果为空 Simditor 会取 textarea 的 placeholder 属性。

- name: "toolbar"
  type: "Boolean / Array"
  default: "true"
  description: |
    是否显示工具栏按钮，可通过数组的形式配置具体显示按钮，支持以下按钮：

    ```coffee
    [
      'title'          # 标题文字
      'bold'           # 加粗文字
      'italic'         # 斜体文字
      'underline'      # 下划线文字
      'strikethrough'  # 删除线文字
      'color'          # 修改文字颜色
      'ol'             # 有序列表
      'ul'             # 无序列表
      'blockquote'     # 引用
      'code'           # 代码
      'table'          # 表格
      'link'           # 插入链接
      'image'          # 插入图片
      'hr'             # 分割线
      'indent'         # 向右缩进
      'outdent'        # 向左缩进
    ]
    ```

- name: "toolbarFloat"
  type: "Boolean"
  default: "true"
  description: |
    是否让工具栏按钮在页面滚动的过程中始终可见。

- name: "toolbarFloatOffset"
  type: "Number"
  default: 0
  description: |
    自定义工具栏浮动的位置。

- name: "toolbarHidden"
  type: "Boolean"
  default: "false"
  description: |
    是否隐藏工具栏，隐藏后 `toolbarFloat` 会失效。

- name: "defaultImage"
  type: "String"
  default: "images/image.png"
  description: |
    编辑器插入混排图片时使用的默认图片。

- name: "tabIndent"
  type: "Boolean"
  default: "true"
  description: |
    是否在编辑器中使用 `tab` 键来缩进。

- name: "params"
  type: "Object"
  default: "{ }"
  description: |
    键值对，在编辑器中增加 hidden 字段（input:hidden），通常用于生成 form 表单的默认参数。可生成如下标签：

    ```html
    <input type="hidden" name="key" value="val" />
    ```

- name: "upload"
  type: "Boolean / Object"
  default: "false"
  description: |
    false 或者键值对，编辑器上传本地文件的配置，键值对可以设置的参数有：

    * `url` 文件上传的接口地址；
    * `params` 键值对，指定文件上传接口的额外参数，上传的时候随文件一起提交；
    * `fileKey` 服务器端获取文件数据的参数名；
    * `connectionCount` 同时上传文件的最大数量；
    * `leaveConfirm` 在文件上传过程中离开页面时提醒的文案。

    键值对参数的默认值：

    ```coffee
    editor = new Simditor
      textarea: $('#editor')
      upload:
        url: ''
        params: null
        fileKey: 'upload_file'
        connectionCount: 3
        leaveConfirm: '正在上传文件，如果离开上传会自动取消'
    ```

    图片上传成功后，服务端需要返回json格式的图片地址：

    ```coffee
    {
      "success": true/false,
      "msg": "上传失败信息", # 可选
      "file_path": "[real file path]"
    }
    ```

- name: "pasteImage"
  type: "false"
  default: "Boolean"
  description: |
    是否允许粘贴上传图片，依赖 `upload` 选项，仅支持 Firefox 和 Chrome 浏览器。
